#include "BoxGame.h"
struct MAP
{
	int *pSrcMap;
	int height;
	int width;
};

int map1[8][8] =
{
	{ FLOOR, FLOOR, WALL, WALL, WALL, WALL, FLOOR, FLOOR },
	{ FLOOR, FLOOR, WALL, FLOOR, FLOOR, WALL, WALL, FLOOR },
	{ WALL,		WALL,	FLOOR,	BOX,	FLOOR,	FLOOR,	WALL,	WALL },
	{ WALL,		FLOOR,	AIM,	FLOOR,	AIM,	BOX,	WALL,	WALL },
	{ WALL,		FLOOR,	FLOOR,	BOX,	PERSON, FLOOR,	FLOOR,	WALL },
	{ WALL,		WALL,	WALL,	WALL,	AIM,	WALL,	FLOOR,	WALL },
	{ FLOOR, FLOOR, FLOOR, WALL, FLOOR, FLOOR, FLOOR, WALL },
	{ FLOOR, FLOOR, FLOOR, WALL, WALL, WALL, WALL, WALL }
};
int map2[8][10] =
{
	{ FLOOR, FLOOR, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR },
	{ FLOOR, WALL, WALL, WALL, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR },
	{ WALL, WALL, AIM, FLOOR, BOX, WALL, WALL, FLOOR, WALL, WALL },
	{ WALL, AIM, AIM, BOX, FLOOR, BOX, FLOOR, FLOOR, PERSON, WALL },
	{ WALL, AIM, AIM, FLOOR, BOX, FLOOR, BOX, FLOOR, WALL, WALL },
	{ WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, FLOOR, WALL, FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, WALL, WALL, WALL, FLOOR },
	{ FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
};
MAP maps[2] =
{
	{ (int*)map1, 8, 8 },
	{ (int*)map2, 8, 10 }


};